<?php if (Mage::getStoreConfigFlag('ajaxscroll/general/useajaxscroll')): ?>
    <?php if (Mage::getStoreConfigFlag('ajaxscroll/general/enabled')): ?>
        <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>ajaxscroll/jquery-1.7.2.min.js"></script>
    <?php endif; ?>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>ajaxscroll/jquery-noconflict.js"></script>
    <!--<script type="text/javascript" src="<?php /*echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);*/?>ajaxscroll/jquery.ias.min.js"></script>-->
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>ajaxscroll/jquery.ias.js"></script>

<?php 
// Get the default setting for grid or list mode
$productListMode = Mage::getStoreConfig('catalog/frontend/list_mode');
if ($productListMode == 'grid-list')
	$productListMode = 'grid';
elseif ($productListMode == 'list-grid')
	$productListMode = 'list';

// Check if this setting is overwritten by the user
if ($this->getRequest()->getParam('mode')) {
	if($this->getRequest()->getParam('mode') == 'grid')
		$productListMode = 'grid';
	else
		$productListMode = 'list';
}
?>
    <?php $itemClass =($productListMode == 'grid')?'.products-grid': '.products-list'; ?>
    <?php $container='.category-products'; ?>

    <script type="text/javascript">
        jQuery.ias({
            container : '<?php echo $container ?>',
            item: '<?php echo $itemClass ?>',
            pagination: '.toolbar .pager',
            next: '.next .next',
            onRenderComplete: function(){
                setGridItemsEqualHeight(jQuery);

            },
            /*onLoadItems: function(data) {
                var items=jQuery(data);
                var itemsHtml=jQuery(data).html();
                curLastItem = jQuery('<?php echo $container ?>').find('<?php echo $itemClass ?>').last();
                curLastItem.find('#ajax-loaded').remove();
                curLastItem.append(itemsHtml);
                return false;
            },*/
            loader: '<img src="<?php echo($this->getSkinUrl('images/ajaxscroll/loader.gif')); ?>" /> <?php echo __('Loading more products, please be patient...'); ?>'
        });
</script>
<?php endif; ?>
