<?php
$_productCollection = $this->getMyCollection();
$category = $this->catName();
$_helper = $this->helper('catalog/output');
$_collectionSize = $this->productsAmount();
$_columnCount = 4; //$this->getColumnCount();
?>
<?php // Grid Mode ?>
<div class="home-container grid-container">

    <div class="<?php if($this->getLayout()->createBlock('cms/block')->setBlockId('grid_2_text_box')->toHtml()){echo ' grid_6 omega';}else{echo ' no-static-block grid_12';} ?>">
	<h1>Populära produkter</h1>
        <ul class="products-grid widget-grid widget-grid-2">
            <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <li class="grid_3 item <?php if($i%2){echo 'odd omega';}else{echo 'alpha';} ?>">
                    <div class="product-img-box">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'base_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?></a>
                    </div>
                </li>
            <?php if ($i+1 == $_collectionSize ) break; $i++; endforeach ?>
        </ul>
    </div>
</div>
<div id="checkpoint-4"></div>