<div class="blogg">
    <div class="blogg-wrapper">
        <h2><a href="/blogg/">Läs vår blogg!</a></h2>
    </div>
</div>
<script type="text/javascript">
    jQuery.getJSON("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>wordpress/wp-json.php/posts")
        .done(function (data) {
            var htmlString = "";
            jQuery.each(data, function (index, entry) {
                htmlString += "<a href =\"" + entry.link + "\">";
                htmlString += "<h4>" + entry.title + "</h4>";
                htmlString += "<p>" + entry.content.substr(0, 100) + "...</p>";
                htmlString += "</a>";
            });
            jQuery(".blogg-wrapper").append(htmlString);
        })
        .fail(function (jqxhr, textStatus, error) {
            var err = textStatus + ", " + error;
            console.log("Request Failed: " + err);
        });
</script>
