<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/mode/markdown/markdown.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/mode/xml/xml.js') ?>"></script>
<script id="script">
    var editorQueue = {};
    var cntQueue = 0;
    document.observe('dom:loaded', function () {
        var prefix = $("prefix");
        addEditor(prefix);
        var suffix = $("suffix");
        addEditor(suffix);
        var htmlText = $("html_text");
        addEditor(htmlText);

    });

    function refreshEditor(editor) {
        editor.refresh();
        editor.save();
    }
    function addEditor(el) {
        var edt = CodeMirror.fromTextArea(el, {
            lineNumbers: true,
            lineWrapping: true,
            mode: "markdown"
        });
        editorQueue[el.id] = edt;
        cntQueue++;
        setTimeout(function () {
            refreshEditor(edt);
        }, 200)
    }
    function processEditorQueue(){
        for(index in editorQueue){
            refreshEditor(editorQueue[index]);
        }

    }
</script>