<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/fold/foldgutter.css') ?>" media="all"/>
<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/dialog/dialog.css') ?>" media="all"/>
<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/theme/monokai.css') ?>" media="all"/>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/search/searchcursor.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/search/search.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/dialog/dialog.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/edit/matchbrackets.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/edit/closebrackets.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/comment/comment.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/wrap/hardwrap.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/fold/foldcode.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/fold/brace-fold.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/mode/javascript.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/keymap/sublime.js') ?>"></script>
<style type="text/css">
    .CodeMirror {
        border-top: 1px solid #eee;
        border-bottom: 1px solid #eee;
        line-height: 1.3;
        height: 500px
    }

    .CodeMirror-linenumbers {
        padding: 0 8px;
    }
</style>
<script>
    var editorQueue = {};
    var cntQueue = 0;
    document.observe('dom:loaded', function () {
        var prefix = $("prefix");
        addEditor(prefix);
        var suffix = $("suffix");
        addEditor(suffix);
        var htmlText = $("html_text");
        addEditor(htmlText);

    });
    function refreshEditor(editor) {
        editor.refresh();
    }
    function addEditor(el) {
        if (el) {
            var edt = CodeMirror(el.up('td'), {
                value: el.value,
                lineNumbers: true,
                mode: "javascript",
                keyMap: "sublime",
                autoCloseBrackets: true,
                matchBrackets: true,
                showCursorWhenSelecting: true,
                theme: "monokai"
            });
            el.hide();
            editorQueue[el.id] = edt;
            cntQueue++;
            setTimeout(function () {
                refreshEditor(edt);
            }, 200)
        }

    }
    function processEditorQueue() {
        for (index in editorQueue) {
            refreshEditor(editorQueue[index]);
            $(index).value = editorQueue[index].getValue();
        }

    }
</script>
