<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/dialog/dialog.css') ?>" media="all"/>
<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/hint/show-hint.css') ?>" media="all"/>
<link rel="stylesheet" type="text/css"
      href="<?php echo $this->getSkinUrl('css/mageplaza/bannerslider/editor/tern/tern.css') ?>" media="all"/>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/mode/javascript.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/dialog/dialog.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/hint/show-hint.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('mageplaza/bannerslider/editor/tern/tern.js') ?>"></script>
<script src="<?php echo "http://ternjs.net/node_modules/acorn/dist/acorn.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/node_modules/acorn/dist/acorn_loose.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/node_modules/acorn/dist/walk.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/doc/demo/polyfill.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/lib/signal.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/lib/tern.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/lib/def.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/lib/comment.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/lib/infer.js" ?>"></script>
<script src="<?php echo "http://ternjs.net/plugin/doc_comment.js" ?>"></script>
<script>
    var editorQueue = {};
    var cntQueue = 0;
    function getURL(url, c) {
        var xhr = new XMLHttpRequest();
        xhr.open("get", url, true);
        xhr.send();
        xhr.onreadystatechange = function () {
            if (xhr.readyState != 4) return;
            if (xhr.status < 400) return c(null, xhr.responseText);
            var e = new Error(xhr.responseText || "No response");
            e.status = xhr.status;
            c(e);
        };
    }

    var server;
    getURL("http://ternjs.net/defs/ecma5.json", function (err, code) {
        if (err) throw new Error("Request for ecma5.json: " + err);
        server = new CodeMirror.TernServer({defs: [JSON.parse(code)]});
        editor.setOption("extraKeys", {
            "Ctrl-Space": function (cm) {
                server.complete(cm);
            },
            "Ctrl-I": function (cm) {
                server.showType(cm);
            },
            "Ctrl-O": function (cm) {
                server.showDocs(cm);
            },
            "Alt-.": function (cm) {
                server.jumpToDef(cm);
            },
            "Alt-,": function (cm) {
                server.jumpBack(cm);
            },
            "Ctrl-Q": function (cm) {
                server.rename(cm);
            },
            "Ctrl-.": function (cm) {
                server.selectName(cm);
            }
        })
        editor.on("cursorActivity", function (cm) {
            server.updateArgHints(cm);
        });
    });
    document.observe('dom:loaded', function () {
        var prefix = $("prefix");
        addEditor(prefix);
        var suffix = $("suffix");
        addEditor(suffix);
        var htmlText = $("html_text");
        addEditor(htmlText);
    });
    function refreshEditor(editor) {
        editor.refresh();
        editor.save();
    }
    function addEditor(el) {
        var edt = CodeMirror.fromTextArea(el, {
            lineNumbers: true,
            mode: "javascript"
        });
        editorQueue[el.id] = edt;
        cntQueue++;
        setTimeout(function () {
            refreshEditor(edt);
        }, 200)
    }
    function processEditorQueue(){
        for(index in editorQueue){
            refreshEditor(editorQueue[index]);
        }

    }
</script>