<ul class="links">
                        <li class=" first" id="top-link-account">
                <a href="<?php echo $this->getUrl('customer/account');?>" title="Skapa konto" class="feature-icon-hover">
                                            <span class="icon force-no-bg-color i-account-w"></span>
                                            <span class="label">Skapa konto</span>
                </a>
            </li>
                        <li id="top-link-login">
                        <?php if (Mage::helper('customer')->isLoggedIn() ): ?>
                <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>" title="Logga out" class="feature-icon-hover">
                                            <span class="icon force-no-bg-color i-logout-w"></span>
                                            <span class="label">Logga ut</span>
                </a>
            <?php else: ?>
                <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" title="Logga in" class="feature-icon-hover">
                                            <span class="icon force-no-bg-color i-login-w"></span>
                                            <span class="label">Logga in</span>
                </a>
            <?php endif; ?>
            </li>
</ul>

