<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Onestepcheckout
 * @version    1.3.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ($this->canShow()): ?>
<div id="aw-onestepcheckout-authentification">
    <div id="aw-onestepcheckout-authentification-container-conform">
        <p id="aw-onestepcheckout-title-description"><?php echo $this->__('please select account type')?></p>
        <div><button type="button" id="aw-onestepcheckout-conform-account-scola-btn" href="javascript:void(0);" class="button"><span><span><?php echo $this->__('School') ?></span></span> </button>
        <button type="button" id="aw-onestepcheckout-conform-account-private-btn" href="javascript:void(0);" class="button"><span><span><?php echo $this->__('Private Person') ?></span></span> </button></div>
    </div>
    

    <div id="aw-onestepcheckout-authentification-container"  class="clearfix">
        <h2 id="school" class="school"><?php echo $this->__('School')?></h2>
		<h2 class="private"><?php echo $this->__('Private Person')?></h2>
        <div id="private" class="private private-div">     
        <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p><?php echo $this->__('Description text for guest checkout') ?></p>
            <!--<p><?php echo $this->__('Register with us for future convenience:') ?></p>-->
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
            <div class="buttons-set">
            <p class="required">&nbsp;</p>
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Buy as privat person') ?></span></span></button>
            <?php else: ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
                    <!-- <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
                </form> -->
            <?php endif; ?>
        </div>
     
</div>
        <form id="aw-onestepcheckout-login-form" action="<?php echo $this->getLoginAjaxAction() ?>" method="post">
        <div id='school' class="school">
            <h3><?php echo $this->__('Create account / login in order to bill the school') ?></h3>
            <p><?php echo $this->__('Description text for login') ?> <a class="pink-link" href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__('Register an account here') ?></a>.</p>
		</div>
    <!--    <div id='private' class="private">
            <h3><?php echo $this->__('Create account / login as a private person') ?></h3>
            <p><?php echo $this->__('Description text for private login') ?> <a class="pink-link"href="<?php echo Mage::getUrl('customer/account/create'); ?>"><?php echo $this->__('Register an account here') ?></a>.</p>
		</div>-->
            <div class="form-list" id="onestepcheckout-login">
                <div class="aw-onestepcheckout-auth-form-block">
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->getUsername() ?>" />
                    </div>
                </div>
                <div class="aw-onestepcheckout-auth-form-block">
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password" id="login-password" name="login[password]" />
                    </div>
                </div>
                <div class="aw-onestepcheckout-auth-form-block">
				    <a id="aw-onestepcheckout-login-forgot-link" href="javascript:void(0);"><?php echo $this->__('Forgot your password?') ?></a><br/>
                    <button type="submit" class="button" id="aw-onestepcheckout-login-submit-btn">
                        <span><span><?php echo $this->__('Login') ?></span></span>
                    </button>
                    
                </div>
                <?php if($this->canFBIShow()): ?>
                <div class="aw-onestepcheckout-auth-form-block" id="aw-onestepcheckout-login-form-block-fbi">
                    <?php echo $this->getChildHtml('fb');?>
                </div>
                <?php endif;?>
            </div>
        </form>
        <form id="aw-onestepcheckout-forgot-password-form" action="<?php echo $this->getForgotPasswordAjaxAction() ?>" method="post">
            <div class="form-list">
                <p><?php echo $this->__('Please enter your email below and we will send you a new password.');?></p>
                <div class="aw-onestepcheckout-auth-form-block">
                    <label for="forgot-password-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="forgot-password-email" name="email" value="<?php echo $this->getUsername() ?>" />
                    </div>
                </div>
                <div class="aw-onestepcheckout-auth-form-block">
                    <button type="submit" class="button" id="aw-onestepcheckout-forgot-password-submit-btn">
                        <span><span><?php echo $this->__('Submit') ?></span></span>
                    </button>
                    <a class="aw-onestepcheckout-forgot-password-back" href="javascript:void(0);"><?php echo $this->__('Return to Login') ?></a>
                </div>
            </div>
        </form>
        <div id="aw-onestepcheckout-forgot-password-success">
            <p><?php echo $this->__('If there is an account associated with email address you will receive an email with a link to reset your password.');?></p>
            <p><?php echo $this->__('Click the link below to return to login.');?></p>
            <div class="aw-onestepcheckout-auth-form-block">
                <a class="aw-onestepcheckout-forgot-password-back" href="javascript:void(0);"><?php echo $this->__('Return to Login') ?></a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var awOSCLoginBlock = new AWOnestepcheckoutLogin({
        containerSelector: '#aw-onestepcheckout-authentification-container',
        forgotPasswordLinkSelector: '#aw-onestepcheckout-login-forgot-link',
        backToLoginLinkSelector: '.aw-onestepcheckout-forgot-password-back',
        loginFormSelector: '#aw-onestepcheckout-login-form',
        forgotPasswordFormSelector: '#aw-onestepcheckout-forgot-password-form',
        forgotPasswordSuccessBlockSelector: '#aw-onestepcheckout-forgot-password-success',
        fbButtonContainerSelector: '#aw-onestepcheckout-login-form-block-fbi',
        fbButtonRequestUrl: <?php echo Zend_Json::encode($this->getFbButtonRequestUrl());?>,
        errorMessageBoxCssClass: 'aw-onestepcheckout-error-msg ',
        overlayConfig: {
            '48px': 'aw-onestepcheckout-overlay aw-onestepcheckout-overlay-48',
            '24px': 'aw-onestepcheckout-overlay aw-onestepcheckout-overlay-24',
            '16px': 'aw-onestepcheckout-overlay aw-onestepcheckout-overlay-16'
        },
        jsErrorMsg: <?php echo Zend_Json::encode($this->__("Oops something's wrong")); ?>
    });
</script>
<script>
        jQuery(function ($) {

           $('#aw-onestepcheckout-general-container').hide();
           $('#aw-onestepcheckout-authentification-container').hide();
           $('#aw-onestepcheckout-conform-account-scola-btn').on('click', function () {
            $('#aw-onestepcheckout-general-container').hide();

            $('#aw-onestepcheckout-authentification-container').show();
            $('.school').show();
            $('.private').hide();
			$('#onestepcheckout-login').show()
           });
           $('#aw-onestepcheckout-conform-account-private-btn').on('click', function () {
            $('#aw-onestepcheckout-general-container').hide();
            $('#aw-onestepcheckout-authentification-container').show();
            $('.school').hide();
            $('.private').show();
			$('#onestepcheckout-login').hide()

           });
           $('#onepage-guest-register-button').on('click',function(){
                $('#aw-onestepcheckout-authentification-container').hide();
                $('#aw-onestepcheckout-general-container').show();
                AWOnestepcheckoutCore.updateNumbers();

           });

        });

</script>
<?php endif;?>
