<?php 
/*****/
$sliderConfig = MAGE::helper('ThemeOptions')->getThemeOptions('headerslider');
/*****/
$show = 0;
if ($sliderConfig ['enabled']):

  /**/
  if ($sliderConfig['onlyhome']):
    if (Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'):
      $show = 1;
    endif;
  else:
    $show = 1;
  endif; 
  /**/

if ($show): ?>
<div class="startpage-banner">
	<div class="container_12">
		<div class="main-container">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner')->toHtml(); ?>	
		</div>
	</div>
</div>
    <?php 
  endif;
endif;