<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
    $grid = MAGE::helper('ThemeOptions')->getThemeOptions('grid' );
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<section class="category-products">
    <?php echo $this->getToolbarHtml() ?>

	<?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

    <?php if ($grid == 'grid_standard'): //////// Standard Grid ?>
    
    <ul class="products-grid">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item <?php if(!($i%4) or ($i==1)): ?>alpha<?php endif; ?> <?php if(!($i%3)): ?>omega<?php endif; ?>">
                <div class="grid-indent">
                    <div class="product-box">
						<a href="<?php echo $_product->getProductUrl() ?>">
							<div class="product-img-box">
	                            <?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductNewLabel($_product); ?>
	                            <div title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(162, 200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
	                        	</div>
							</div>   
                            <h2 class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>                    
						</a>
                     	<p><?php echo $this->htmlEscape($_product->getData('mini_description')); ?></p> 
                        	<?php echo $this->getPriceHtml($_product, true) ?>
	                        <?php if($_product->getRatingSummary()): ?>
	                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	                        <?php endif; ?>
                      
                </div>      
						<div class="actions">
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                
                            </ul>
						
                            <?php if($_product->isSaleable()): ?>
                                <!-- START add to cart button with quantity --> 
                                <div class="add-to-cart">
                                    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit()"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    </form>

                                    <script type="text/javascript">
                                         var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
                                         productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function(){
                                         if (this.validator.validate()) {
                                                 this.form.submit();
                                             }
                                         }.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
                                    </script>
                                </div>
                                <!-- END add to cart button with quantity -->

                                <!-- START add to cart button without quantity -->
                                <!-- <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> -->
                                <!-- END add to cart button without quantity -->
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        </div>
                    </div>
            </li>
            <?php $i++; endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>    
    <?php endif; ?>
</section>
<section class="zblocks-section">
<div class="row">
<div id="blog-container"> 
	<div class="top-line"></div>
	<?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_1')->toHtml() ?>
    <div class="bottom-line"></div>
</div>
<?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_2')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_3')->toHtml() ?>
</div>
<div class="row">
<div id="fb-root"></div>

<script>(function(d, s, id) {

  var js, fjs = d.getElementsByTagName(s)[0];

  if (d.getElementById(id)) return;

  js = d.createElement(s); js.id = id;

  js.src = "//connect.facebook.net/sv_SE/all.js#xfbml=1&appId=385434821562561";

  fjs.parentNode.insertBefore(js, fjs);

}(document, 'script', 'facebook-jssdk'));</script>

 

<div class="fb-like-box" data-href="http://www.facebook.com/majemaiforskolan?ref=hl" data-width="532" data-height="450" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="true" data-show-border="true"></div>
<?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_4')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_5')->toHtml() ?>
<div class="zblock-box-dynamics-container">
    <div class="top-line"></div>
    <?php echo $this->getLayout()->createBlock('zblocks/block')->setPosition('forskolan_block_6')->toHtml() ?>
    <div class="bottom-line"></div>
</div>
</div>
</section>
<?php endif; ?>
