<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $theme = $this->helper('fortis');
    $helperSnippets = $this->helper('fortis/rsnippets');

    //CSS classes based on product type
    $productTypeId = $_product->getTypeId();
    $productType = '';
    if ($productTypeId === 'simple') {
        $productType = 'simple';
    } elseif ($productTypeId === 'bundle') {
        $productType = 'bundle';
    } elseif ($productTypeId === 'grouped') {
        $productType = 'grouped';
    }
    $productTypeClasses = '';
    if ($productType !== '')
    {
        $productTypeClasses .= ' is-type-'.$productType;
    }
    if ($_product->isAvailable() === false)
    {
        $productTypeClasses .= ' is-out-of-stock';
    }

    //Rich snippets
    $useRichSnippets = ($helperSnippets->isEnabledOnProductPage() && $productTypeId !== 'grouped');
    $priceProperties = '';
    if ($useRichSnippets)
    {
        $priceProperties = $helperSnippets->getPriceProperties($_product); //Has to be called before getOfferItemscope
    }
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view pv-top-outline" <?php if ($useRichSnippets) echo $helperSnippets->getProductItemscope(); ?>>

    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="product-view-form">
        <div class="product-top-wrapper-cover-top"></div>
        <div class="product-top-wrapper">
        <div class="product-top-wrapper2">
        <div class="product-top-wrapper3 clearer"> <!-- for IE8 fixes -->



        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <div id="">

            </div>
        </div>
        
        <?php
            //Product collaterals
            $section = array();
            
            //Related products. $section['related'] is set only if related products (or replacement) exist
            $replaceRelated = $theme->getCfg('product_page/replace_related');
            if ($replaceRelated == 1) //don't replace with static block
            {
                if ($tmpHtml = trim($this->getChildHtml('catalog.product.related')))
                    $section['related'] = $tmpHtml;
                //$section['related'] = trim($this->getChildHtml('catalog.product.related'));
            }
            elseif ($replaceRelated == 2) //if related is empty, replace with static block
            {
                if ($tmpHtml = trim($this->getChildHtml('catalog.product.related')))
                    $section['related'] = $tmpHtml;
                else //related empty
                    if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
                        $section['related'] = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
            }
            elseif ($replaceRelated == 3) //replace with static block
            {
                if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
                    $section['related'] = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
            }
    
            //Up-sell products. $section['upsell'] is set only if up-sell products (or replacement) exist
            $replaceUpsell = $theme->getCfg('product_page/replace_upsell');
            if ($replaceUpsell == 1) //don't replace with static block
            {
                if ($tmpHtml = trim($this->getChildHtml('upsell_products')))
                    $section['upsell'] = $tmpHtml;
                //$section['upsell'] = $this->getChildHtml('upsell_products');
            }
            elseif ($replaceUpsell == 2) //if upsell is empty, replace with static block
            {
                if ($tmpHtml = trim($this->getChildHtml('upsell_products')))
                    $section['upsell'] = $tmpHtml;
                else //upsell empty
                    if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
                        $section['upsell'] = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
            }
            elseif ($replaceUpsell == 3) //replace with static block
            {
                if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
                    $section['upsell'] = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
            }
            
            
            
            //Assign related products to selected position
            if (isset($section['related']))
            {
                $relatedPosition = $theme->getCfg('product_page/related_position');
                //TODO:remove: $relatedPosition = 11;
                switch ($relatedPosition)
                {
                    case 10:
                        $p['secondaryCol'][0] = $section['related'];
                        break;
                    case 11:
                        $p['secondaryCol'][1] = $section['related'];
                        break;
                    case 20:
                        $p['collatSecondaryCol'] = $section['related'];
                        break;
                }
            }
            
            
            
            //Width (in grid units) of product page sections
            $imgColUnits                    = $theme->getCfg('product_page/image_column');
            $primaryColUnits                = $theme->getCfg('product_page/primary_column');
            $secondaryColUnits              = $theme->getCfg('product_page/secondary_column');
            $container2ColUnits             = $imgColUnits + $primaryColUnits;
            $collatPrimaryColUnits          = $imgColUnits + $primaryColUnits;
            $collatSecondaryColUnits        = $secondaryColUnits;

            //If no secondary column
            if (empty($secondaryColUnits))
            {
                $primaryColUnits            += 12 - ($imgColUnits + $primaryColUnits);
                $container2ColUnits         = $imgColUnits + $primaryColUnits;
                $collatPrimaryColUnits      = 9;
                $collatSecondaryColUnits    = 3;
            }

            //If no related products at the side of the tabs, stretch collateral primary column
            if (!isset($p['collatSecondaryCol']))
            {
                $collatPrimaryColUnits      = 12;
                $collatSecondaryColUnits    = 0;
            }
            //If no related products in the secondary column, stretch container2 (product options)
            if (!isset($p['secondaryCol']))
            {
                $container2ColUnits = 12;
            }
            
            //Grid classes
            $imgColGridClass                = 'grid12-' . $imgColUnits;
            $primaryColGridClass            = 'grid12-' . $primaryColUnits;
            $secondaryColGridClass          = 'grid12-' . $secondaryColUnits;
            $container2ColGridClass         = 'grid12-' . $container2ColUnits;
            $collatPrimaryColGridClass      = 'grid12-' . $collatPrimaryColUnits;
            $collatSecondaryColGridClass    = 'grid12-' . $collatSecondaryColUnits;
            if (empty($secondaryColUnits))
            {
                $secondaryColGridClass  = '';
            }
        ?>

        <div class="product-img-column <?php echo $imgColGridClass; ?>">
            <?php echo $this->getChildHtml('media') ?>
            <?php //Product labels
                echo $this->helper('fortis/labels')->getLabels($_product);
            ?>
			<?php if ($_product->getLinkToExample()) : ?>
                <a class="preview-link" target="_blank" href="<?php echo $this->htmlEscape($_product->getData('link_to_example')); ?>">Bläddra i boken</a>
            <?php endif; ?>
        </div>
        
        <div class="product-shop <?php echo $primaryColGridClass; ?>">

            <div class="product-name">
                <h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
			<?php if ($_product->isDigitalProduct == 1) : ?>
                    <div class="degital_image" > <img src="<?php echo $this->getSkinUrl('images/ikon_smartboard.png') ?>"/> </div>
                    <div style="clear:both;"> </div>
                <?php endif; ?>
                <div class="product-box">
                    <ul>
                        <?php if ($_product->getSchoolYear()) : ?>
                            <li><strong>Årskurs:</strong> <?php echo $this->htmlEscape($_product->getData('school_year')); ?></li>
                        <?php endif; ?>
                        <li><strong>Beställnr:</strong> <?php echo nl2br($_product->getSku()) ?></li>
                        <?php if ($_product->getIsbnNr()) : ?>
                            <li><strong>ISBN:</strong> <?php echo $this->htmlEscape($_product->getData('isbn_nr')); ?></li>
                        <?php endif; ?>
                        <?php if ($_product->getProductSize()) : ?>
                            <li><strong>Produktstorlek:</strong> <?php echo $this->htmlEscape($_product->getData('product_size')); ?></li>
                        <?php endif; ?>
                        <?php if ($_product->isDigitalProduct == 1 && $_product->licensperiod != '') : ?>
                            <li><strong>Licensperiod:</strong> <?php echo $_product->licensperiod; ?></li>
                        <?php endif; ?>
                        <?php if ($_product->isAvailable()): ?>
                            <li class="availability in-stock"><strong><?php echo $this->__('Availability:') ?></strong> <?php echo $this->__('In stock') ?></li>
                            <meta itemprop="availability" content="http://schema.org/InStock">
                        <?php else: ?>
                            <li class="availability out-of-stock"><strong><?php echo $this->__('Availability:') ?></strong> <?php echo $this->__('Out of stock') ?></li>
                            <meta itemprop="availability" content="http://schema.org/OutOfStock">
                        <?php endif; ?>
                    </ul>
                </div>
            
            <?php echo $this->getReviewsSummaryHtml($_product, false, true); //reviews ?>

            <?php if ($sku = $_product->getSku()): ?>
                <?php if ($theme->getCfg('product_page/sku')): ?>
                    <div class="sku">
                        <span class="label"><?php echo $this->__('SKU'); ?>: </span>
                        <span class="value"><?php echo $sku; ?></span>
                    </div>
                <?php endif; ?>
                <?php if ($useRichSnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('alert_urls'); //alerts ?>
            
            <?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
                <div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
            <?php endif; ?>

            <?php if($_product->getTypeId()!='grouped'):?>
                <div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>
                    <div class="product-type-data clearer<?php echo $productTypeClasses; ?>">
                        <?php echo $this->getChildHtml('product_type_data'); ?>
                    </div>
                    <?php echo $this->getTierPriceHtml(); //tier prices ?>
                    <?php echo $priceProperties; ?>
                </div> <?php //end: offers ?>
                <?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
                    <?php if($_product->isSaleable()): ?>
                        <div class="add-to-box">
                            <?php echo $this->getChildHtml('addtocart') ?>
                        </div>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                <?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
                    <div class="container1-wrapper"><?php echo $container1_html; ?></div>
                <?php endif; ?>
            <?php endif;?>
            
          
            
            <?php echo $this->getChildHtml('other'); ?>

            <?php if ($tmpHtml = $this->getChildHtml('block_product_primary_bottom')): ?>
                <div class="feature-wrapper top-border block_product_primary_bottom"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>
            
            <?php if ($tmpHtml = $this->getChildHtml('product_primary_bottom_placeholder')): //Placeholder for extensions ?>
                <div class="feature-wrapper top-border"><?php echo $tmpHtml; ?></div>
            <?php endif; ?>

        </div> <!-- end: product-shop -->
        
       

        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
            <?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
                <div class="box-additional <?php echo $container2ColGridClass; ?>">
                    <div class="container2-wrapper"><?php echo $container2_html; ?></div>
                </div>
            <?php endif; ?>
        <?php endif; ?>



        </div> <!-- end: product-top-wrapper3 -->
        </div> <!-- end: product-top-wrapper2 -->
        </div> <!-- end: product-top-wrapper -->
        <div class="product-top-wrapper-cover-bottom"></div>
        <?php if($_product->getTypeId()=='grouped'):?>
            <?php echo $this->getChildHtml('product_type_data'); ?>
            <?php if (!$this->hasOptions()):?>
                <div class="product-type-block">
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>

    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>

    <?php if ($_product->getShortDescription()): ?>
        <div class="short-description">
            <div class="std" itemprop="description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
        </div>
    <?php endif;?>

    <div class="collapsible ">
    <span class="opener custom">Läs mer</span><br>
    <h6 class="block-title"></h6>
    <div class="block-content">

        <div class="box-additional box-tabs">
            <?php $info_tabs_html = trim($this->getChildHtml('info_tabs'));
                if ($info_tabs_html) echo $info_tabs_html; ?>

            <?php //Open the "Reviews" tab, when "X Review(s)" or "Be the first to review this product" links are clicked ?>
            <script type="text/javascript">
            //<![CDATA[
                jQuery(function($){$("#goto-reviews, #goto-reviews-form").click(function(){if($("#product-tabs").hasClass("accor")){$("#product-tabs .tabs-panels").data("tabs").click($(".tabs-panels .acctab").index($("#acctab-tabreviews")))}else{$("#product-tabs .tabs").data("tabs").click($("#tab-tabreviews").index())}})});
            //]]>
            </script>
            
            <?php echo $this->getChildHtml('product_additional_data') ?>
        </div> <!-- end: box-tabs -->

        <?php if ($_product->getlgr11Descr()): ?>
        <div class="product-collateral">
            <h2>Koppling till LGR11</h2>
            <div class="box-collateral">
                <?php echo $this->getProduct()->getlgr11Descr(); ?>
            </div>
        </div>
        <?php endif; ?>
    
    </div>
    </div>

    <?php
    // instantiate the tags class for products
    $_tags = new Mage_Tag_Block_Product_List();
    ?>
    <p class="product-tag-title"><strong>Etiketter: </strong></p>
    <ul class="product-tags">
    <?php foreach($_tags->getTags() as $tag):?>
        <li><a href="<?=$tag->getTaggedProductsUrl()?>"><?=$tag->getName()?>, </a></li>
    <?php endforeach;?>
    </ul>

    
    <?php if (isset($p['collatSecondaryCol'])): ?>
        <div class="box-additional box-sidebar custom-sidebar-right <?php echo $collatSecondaryColGridClass; ?>">
            <div><?php echo $p['collatSecondaryCol']; ?></div>
        </div>
    <?php endif; ?>
         
    <?php if (isset($section['upsell'])): ?>
        <div class="box-additional box-up-sell <?php echo $collatPrimaryColGridClass; ?>"><?php echo $section['upsell']; ?></div>
    <?php endif; ?>


</div> <!-- end: product-view -->
<!-- <div class="series left">
        <?php //echo $this->getChildHtml('product_series'); ?>
    </div> -->

<script type="text/javascript">
   Event.observe(window, "load", function(){
        var totalQty = 1;
        var vname = '<?php echo Mage::registry('option_name'); ?>';
        var vlname = '<?php echo Mage::registry('option_lname'); ?>';
        var vemail = '<?php echo Mage::registry('option_email');?>';
        var dlHtml = $$('dl.last').first().innerHTML;
        $('qty').observe('keyup', function(event) {
            qty = $(this).value;
           
            
           /* if(totalQty != qty)
            {
                var html = '';
                 if(totalQty > qty)
                {
                    var diff = qty-1;
                    
                }               
                else if(totalQty < qty)
                {
                    var diff =qty-1;
                }               
                for(var i=0;i<1;i++)
                {*/
                    html += '<dt class="dt-label">Paket-'+(i+2)+'</dt><dd></dd><dt><label class="required"><em>*</em>Förnamn#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vname+'_'+i+'_text" class="input-text required-entry  product-custom-option" name="options['+vname+'_'+i+']" value="" type="text"></div></dd><dt><label class="required"><em>*</em>Efternamn#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vlname+'_'+i+'_text" class="input-text required-entry  product-custom-option" name="options['+vlname+'_'+i+']" value="" type="text"></div></dd><dt><label class="required"><em>*</em>E-post (användarnamn)#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vemail+'_'+i+'_text" class="input-text required-entry  product-custom-option validate-email" name="options['+vemail+'_'+i+']" value="" type="text"></div></dd>';
                }
                try{
                    $$('dl.last').first().innerHTML = dlHtml+html; 
                }
                  catch(e)
                  {
                    alert(e.message);
                  }  
                /*totalQty = qty;   
            }*/
        });

        /*Event.observe($('qty'), 'change', function(e){
            qty = $(this).value;
            
            if(totalQty != qty)
            {
                var html = '';
                 if(totalQty > qty)
                {
                    var diff = qty-1;
                    
                }               
                else if(totalQty < qty)
                {
                    var diff =qty-1;
                }               
                for(var i=0;i<diff;i++)
                {
                    html += '<dt class="dt-label">Paket-'+(i+2)+'</dt><dd></dd><dt><label class="required"><em>*</em>Förnamn#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vname+'_'+i+'_text" class="input-text required-entry  product-custom-option" name="options['+vname+'_'+i+']" value="" type="text"></div></dd><dt><label class="required"><em>*</em>Efternamn#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vlname+'_'+i+'_text" class="input-text required-entry  product-custom-option" name="options['+vlname+'_'+i+']" value="" type="text"></div></dd><dt><label class="required"><em>*</em>E-post (användarnamn)#'+(i+2)+'</label></dt><dd><div class="input-box"><input id="options_'+vemail+'_'+i+'_text" class="input-text required-entry  product-custom-option validate-email" name="options['+vemail+'_'+i+']" value="" type="text"></div></dd>';
                }
                try{
                    $$('dl.last').first().innerHTML = dlHtml+html; 
                }
                  catch(e)
                  {
                    alert(e.message);
                  }  
                totalQty = qty;   
            }
        });*/

    });
</script>