<?php $_helper = Mage::Helper('attigo_slider'); ?>
<?php if ($_helper->getConfig('general/is_active')):?>
<link
	rel="stylesheet" type="text/css"
	href="<?php echo $this->getSkinUrl('attigo/css/template/simple-slider.css')?>" />
<?php $_slider = $this->getSlider(); ?>
<?php if($_slider->getIsPublish()==1):?>
<div id="colorbox-items">
	<a id="test-link" class="colorboxSlider openBoxButton"
		href="#simple-slider-<?php echo $_slider->getId(); ?>" rel="">Click me
		to load slider in lightbox</a>
</div>
<div style="display: none;">
	<div id="simple-slider-<?php echo $_slider->getId(); ?>"
		class="simple-slider royalSlider rsDefault" style="hight: 300px;">
		<?php $_slides =  $this->getslideCollection(); ?>
		<?php foreach($_slides as $_slide) : ?>
		<div>
			<?php $video = "";
			if ($_slide->getVideoUrl() !=""){
				 $video="data-rsVideo=\"".$_slide->getVideoUrl()."\"";
				 }
				 ?>
			<?php if($_slide->getSlideLink()):?>
				<a href="<?php echo $_slide->getSlideLink();?>"> 
			<?php endif; ?> 
				<img class="rsImg" src="<?php echo $_slide->getImageUrl();?>" alt="" <?php echo $video; ?> />
			 <?php if($_slide->getSlideLink()):?>
				</a>
			<?php endif; ?>
			<?php  $textBlock = Mage::helper('core')->jsonDecode($_slide->getConfig()); ?>
			<?php if(count($textBlock)<=0)
		    {
		    	$textBlock = array();
		    } 
    	 ?>
			<?php foreach($textBlock as $_block) :  ?>
			<?php 
			$style=array();
			if($_block['width']!="")
				$style[] = 'width:'.$_block['width'];
			if($_block['height']!="")
				$style[] = 'height:'.$_block['height'];
			if($_block['top']!="")
				$style[] = 'top:'.$_block['top'];
			if($_block['left']!="")
				$style[] = 'left:'.$_block['left'];
			?>
			<div class="bContainer" style="position:absolute;<?php echo implode(";",$style); ?>">
				<?php 
				$effect=array();
				if($_block['fadeEffect']!="")
					$effect[] = 'data-fade-effect="'.$_block['fadeEffect'].'"';
				if($_block['moveEffect']!="")
					$effect[] = 'data-move-effect="'.$_block['moveEffect'].'"';
				if($_block['moveOffset']!="")
					$effect[] = 'data-move-offset="'.$_block['moveOffset'].'"';
				if($_block['speed']!="")
					$effect[] = 'data-speed="'.$_block['speed'].'"';
				if($_block['easing']!="")
					$effect[] = 'data-easing="'.$_block['easing'].'"';
				if($_block['delay']!="")
					$effect[] = 'data-delay="'.$_block['delay'].'"';
				?>
				<span class="rsABlock txtCent" <?php echo implode(" ",$effect); ?>><?php echo $_block['text']; ?>
				</span>
			</div>
			<?php endforeach; ?>
		</div>
		<?php endforeach; ?>
	</div>
</div>
<script type="text/javascript">

jq183(document).ready(function($) {
    
$('#simple-slider-<?php echo $_slider->getId(); ?>').royalSlider({
  imageScaleMode: 'fill',
  video: {
    autoHideControlNav: true
  },
				
}); 
	var win = $(window),
      w,
      cContent = $('#cboxLoadedContent'),
      currRs;
	//  $("#test-link").colorbox({width:"100%", height:"300px", inline:true, href:"#simple-slider-<?php echo $_slider->getId(); ?>"});
      
  $('#colorbox-items').on('click', '.colorboxSlider', function(e) {
      e.preventDefault();
      $.colorbox({
          inline:true,
          preloading: true,
          modal: true,
          transition: 'none',
          speed: 0,
          onComplete: function(e) {
            currRs = $('#cboxLoadedContent').find('.royalSlider').royalSlider({
              imageScaleMode: 'fill',
              keyboardNavEnabled: true,
              video: {
                autoHideControlNav: true
              }
            }).data('royalSlider');
            updateLightboxSize();

          },
          href:$(this).attr('href')
      });
      return false;
  });

  win.resize( function() {
     updateLightboxSize();
  });

  // dynamic lightbox resizing
  function updateLightboxSize() {
      // define sze of lightbox
      w = win.width();
      if(w > 1200) {
        w = '100%';
      } else if(w < 800) {
        w = '90%';
      } else {
        w = '60%';
      }
       $.colorbox.resize({
           width: w
       });
      if(currRs) {
        currRs.updateSliderSize();
      }
      // fix scrolbar space
      setTimeout(function() {
        $.colorbox.resize({
           width: w
        });
      },1);

  }
        
		});
		</script>
<?php endif; ?>
<?php endif; ?>