<?php $_helper = Mage::Helper('attigo_slider'); ?>
<?php if ($_helper->getConfig('general/is_active')):?>
<link
	rel="stylesheet" type="text/css"
	href="<?php echo $this->getSkinUrl('attigo/css/template/visibleNearby.css')?>" />
<?php $_slider = $this->getSlider(); ?>
<?php if($_slider->getIsPublish()==1):?>
<div id="gallery-1-<?php echo $_slider->getId(); ?>"
	class="gallery-1 royalSlider rsDefault visibleNearby">
	<?php $_slides =  $this->getslideCollection(); ?>
	<?php foreach($_slides as $_slide) : ?>
	<div class="rsContent">
		<?php $video = "";
		if ($_slide->getVideoUrl() !=""){
		  $video="data-rsVideo=\"".$_slide->getVideoUrl()."\"";
		  }
		  ?>

		<?php  $_slideImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_slide->getBgimageName(); ?>
		<?php if($_slide->getSlideLink()):?>
			<a href="<?php echo $_slide->getSlideLink();?>"> 
		<?php endif; ?>
			<img class="rsImg" src="<?php echo $_slide->getImageUrl();?>" alt="" <?php echo $video; ?> href="$_slideImage">
		<?php if($_slide->getSlideLink()):?>
			</a>
		<?php endif; ?>
		<?php  $textBlock = Mage::helper('core')->jsonDecode($_slide->getConfig()); ?>
		<?php if(count($textBlock)<=0)
		    {
		    	$textBlock = array();
		    } 
    	 ?>
		<?php foreach($textBlock as $_block) :  ?>
		<?php 
		$style=array();
		if($_block['width']!="")
			$style[] = 'width:'.$_block['width'];
		if($_block['height']!="")
			$style[] = 'height:'.$_block['height'];
		if($_block['top']!="")
			$style[] = 'top:'.$_block['top'];
		if($_block['left']!="")
			$style[] = 'left:'.$_block['left'];
		?>
		<div class="bContainer" style="position:absolute;<?php echo implode(";",$style); ?>">
			<?php 
			$effect=array();
			if($_block['fadeEffect']!="")
				$effect[] = 'data-fade-effect="'.$_block['fadeEffect'].'"';
			if($_block['moveEffect']!="")
				$effect[] = 'data-move-effect="'.$_block['moveEffect'].'"';
			if($_block['moveOffset']!="")
				$effect[] = 'data-move-offset="'.$_block['moveOffset'].'"';
			if($_block['speed']!="")
				$effect[] = 'data-speed="'.$_block['speed'].'"';
			if($_block['easing']!="")
				$effect[] = 'data-easing="'.$_block['easing'].'"';
			if($_block['delay']!="")
				$effect[] = 'data-delay="'.$_block['delay'].'"';
			?>
			<span class="rsABlock txtCent" <?php echo implode(" ",$effect); ?>><?php echo $_block['text']; ?>
			</span>
		</div>
		<?php endforeach; ?>
	</div>
	<?php endforeach; ?>
</div>
<script>
		
		jq183(document).ready(function($) {
			var si = $('#gallery-1-<?php echo $_slider->getId(); ?>').royalSlider({
    addActiveClass: true,
				
				<?php if ($_slider->getConfigValue('auto_play')): ?> 
				 autoPlay:{
							enabled:true,
							stopAtAction: <?php echo $_slider->getConfigValue('stop_action'); ?>,
							pauseOnHover: <?php echo $_slider->getConfigValue('pause_onhover'); ?>,
							<?php if ($_slider->getConfigValue('delay')): ?>
							delay: <?php echo $_slider->getConfigValue('delay'); ?>,
							<?php endif ?>
				 },
				 <?php endif ?>
				controlsInside: <?php echo $_slider->getConfigValue('controls_inside'); ?>,
				fullscreen: {
						enabled: <?php echo $_slider->getConfigValue('fullscreenenabled'); ?>,
						keyboardNav: <?php echo $_slider->getConfigValue('fullscreenkeyboardNav'); ?>,
						buttonFS: <?php echo $_slider->getConfigValue('buttonFS'); ?>,
						nativeFS: <?php echo $_slider->getConfigValue('nativeFS'); ?>,
				},
   

   arrowsNav: false,
    controlNavigation: 'none',
    autoScaleSlider: true, 
    autoScaleSliderWidth: 960,     
    autoScaleSliderHeight: 340,
    loop: true,
    fadeinLoadedSlide: false,
    
    keyboardNavEnabled: true,
	globalCaption: true,
    globalCaptionInside: false,

    visibleNearby: {
      enabled: true,
      centerArea: 0.5,
      center: true,
      breakpoint: 650,
      breakpointCenterArea: 0.64,
      navigateByCenterClick: true
    }
  }).data('royalSlider');

  // link to fifth slide from slider description.
  $('.slide4link').click(function(e) {
    si.goTo(4);
    return false;
  });
		});
		</script>
<?php endif; ?>
<?php endif; ?>