<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php echo $this->getChildHtml('login_before')?>
<div class="grid_5 alpha">
    <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
        <p><?php echo $this->__('Register with us for future convenience:') ?></p>
    <?php else: ?>
        <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
        <?php echo $this->__('Register with us for future convenience:') ?></p>
        <ul>
            <li><?php echo $this->__('Fast and easy check out') ?></li>
            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
        </ul>
    <?php endif; ?>
    
    <div class="buttons-set">
        <p class="required">&nbsp;</p>
        <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
    </div>
</div>
<div class="grid_6 omega">
    <h3><?php echo $this->__('Login') ?></h3>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
    <fieldset>
        <h4><?php echo $this->__('Already registered?') ?>/<?php echo $this->__('Please log in below:') ?></h4>

        <ul class="form-list">
            <li>
                <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                </div>
            </li>
            <li>
                <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </fieldset>
    </form>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
    </div>
</div>
<div class="clear"></div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
