<?php 
$show = 0;
    if (Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'):
      $show = 1;
    endif;
  /**/

if ($show): ?>
<div class="startpage-banner">
	<div class="container_12">
		<div class="main-container">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner')->toHtml(); ?>	
		</div>
	</div>
</div>
<?php  endif; ?>