<?php
/**
 * Activo Extensions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Activo Commercial License
 * that is available through the world-wide-web at this URL:
 * http://extensions.activo.com/license_professional
 *
 * @copyright   Copyright (c) 2014 Activo Extensions (http://extensions.activo.com)
 * @license     Commercial
 */

$enabled = Mage::getStoreConfig('activo_adwordsconversion/remarketing_global/remarketing_enabled');
if($enabled)
{
?>
<script type="text/javascript">
	var google_tag_params = <?php echo $this->getParams(); ?>;
</script>
<script type="text/javascript">
/* <![CDATA[ */
	var google_conversion_id = <?php echo $this->getGoogleConversionId(); ?>;
	var google_custom_params = window.google_tag_params;
	var google_remarketing_only = <?php echo $this->getGoogleRemarketingOnly(); ?>;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?php echo $this->getGoogleConversionId(); ?>/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript> 
<?php } ?>

