<?php $_helper = Mage::Helper('attigo_slider'); ?>
<?php if ($_helper->getConfig('general/is_active')):?>
<?php $_slider = $this->getSlider(); ?>
		<?php if($_slider && $_slider->getIsPublish()==1):?>
<style type="">
.royalSlider {
  width: <?php echo $_slider->getConfigValue('scale_width'); ?>;
  height: <?php echo $_slider->getConfigValue('scale_height').'px'; ?>;
}
</style>        
		
		<?php include 'template'.DS. ($_slider->getConfigValue('slider_type').'.phtml'); ?>
	<?php endif; ?>
<?php endif; ?>