<?php
/**
 * Use this template to display the sidebar menu inside static blocks and pages.
 */
?>
<?php
    $helper = Mage::helper('ultramegamenu');
    $visibilityClass = $helper->getCfg('sidemenu/hide_on_mobile') ? ' hide-below-768' : '';

    //Get starting category - a point where traverse begins
    $categoryId = $this->getParent();
    if ($categoryId === NULL) //Param not set
    {
        $categoryId = $helper->getCfg('sidemenu/parent');
    }

    //Get depth of recursion - how many levels of subcategories retrieve
    $depth = $this->getDepth();
    if ($depth === NULL) //Param not set
    {
        $depth = intval($helper->getCfg('sidemenu/depth'));
    }
    else
    {
        $depth = intval($depth);
    }

    

    //    $url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
    //
    //    if (strpos($url,'laromedel') !== false) {
    //        $categoryId = 8;
    //
    //    } else if (strpos($url,'kalendrar') !== false){
    //        $categoryId = 35;
    //    } else {
    //        $categoryId = null;
    //    }
    
    $currentCategory = Mage::registry('current_category');
    //$currentCategory = $this->getCurrentCategory()->getName();
    if ($currentCategory != null)
    {
        if (strpos($currentCategory ->geturl_path(),'laromedel') !== false) {
            $categoryId = 8;

        } else if (strpos($currentCategory ->geturl_path(),'kalendrar') !== false){
            $categoryId = 35;
        }
       
    }
    else
    {
        $categoryId = 2;
    }
    
    //Render categories menu HTML
    $html = $this->renderMe(TRUE, $categoryId, $depth);
    if (!$html)
    {
        return '';
    }
?>
<div class="block block-vertnav<?php echo $visibilityClass; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->renderBlockTitle(); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="accordion accordion-style1 vertnav vertnav-side clearer"> <?php //Class "vertnav-side" left for backward compatibility ?>
            <?php
                //echo $this->getCurrentCategory()->getId();
            if ($currentCategory != null)
             {
                if (strpos($currentCategory->geturl_path(),'laromedel') !== false)
                {
                    echo $html;
                }
                else if (strpos($currentCategory->geturl_path(),'kalendrar') !== false)
                {
                    echo $html;
                }
             }
             else
             {
                    echo $html;
             }


             ?>
        </ul>
    </div>
</div>
